version: "3"
services:
  georocket:
    image: georocket/georocket
    command: server
    volumes:
      - ./conf/georocket_postgresql_full:/usr/local/georocket/conf
    links:
      - postgresql
    environment:
      FLYWAY_CONNECT_RETRIES: 60
      FLYWAY_CONNECT_RETRIES_INTERVAL: 10
    ports:
      - 63020

  postgresql:
    image: postgis/postgis
    environment:
      POSTGRES_DB: georocket
      POSTGRES_PASSWORD: mysecretpassword
