[package]
name = "testsupport"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
testcontainers = "0.16.3"
testcontainers-modules = { version = "0.4.3", features = ["postgres"] }

[dev-dependencies]
postgres = "0.19.7"

[features]
default = []
postgis = []
