version: "3"
services:
  georocket:
    image: georocket/georocket
    command: server
    volumes:
      - ./conf/georocket_s3:/usr/local/georocket/conf
    links:
      - s3
      - mongo
    ports:
      - 63020

  s3:
    image: minio/minio
    command: server /data
    ports:
      - 9000

  mongo:
    image: mongo
