version: "3"
services:
  georocket:
    image: georocket/georocket
    command: server
    volumes:
      - ./conf/georocket_postgresql:/usr/local/georocket/conf
    links:
      - postgresql
      - mongo
    ports:
      - 63020

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: georocket
      POSTGRES_PASSWORD: mysecretpassword

  mongo:
    image: mongo
