[workspace]
resolver = "2"

members = [
    "georocket",
    "indexing",
    "geo-testcontainer",
    "types",
    "import",
    "query",
    "migrations",
]

[workspace.dependencies]
import = { path = "import" }
indexing = { path = "indexing" }
types = { path = "types" }
migrations = { path = "migrations", features = ["postgis", "tokio-postgres"] }
