version: "2"
services:
  integration-tester:
    build: .
    command: h2
    links:
      - georocket_h2

  georocket_h2:
    image: georocket/georocket
    volumes:
      - ./conf/georocket_h2:/usr/local/georocket-server/conf
