[package]
name = "georocket"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
ariadne.workspace = true
clap.workspace = true
georocket-core.workspace = true
mime_guess.workspace = true
