version: "2"
services:
  integration-tester:
    build: .
    command: s3
    container_name: ci-integration-tester
    links:
      - georocket_s3
      - s3

  georocket_s3:
    image: georocket/georocket
    command: server
    volumes:
      - ./conf/georocket_s3:/usr/local/georocket/conf
    links:
      - s3
      - mongo

  s3:
    image: minio/minio
    command: server /data

  mongo:
    image: mongo
