version: "2"
services:
  integration-tester:
    build: .
    command: h2
    container_name: ci-integration-tester
    links:
      - georocket_h2

  georocket_h2:
    image: georocket/georocket
    command: server
    volumes:
      - ./conf/georocket_h2:/usr/local/georocket/conf
    links:
      - mongo

  mongo:
    image: mongo
