[package]
name = "georocket"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
import.workspace = true
tokio = { version = "1.36", features = ["rt"] }
