version: "3"
services:
  georocket:
    image: georocket/georocket
    command: server
    volumes:
      - ./conf/georocket_h2:/usr/local/georocket/conf
    links:
      - mongo
    ports:
      - 63020

  mongo:
    image: mongo
