name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rust

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test
