name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rustfmt and clippy
        run: rustup component add rustfmt clippy

      # Cache dependencies - must be run after rustup
      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-features --all-targets --no-deps -- -Dwarnings

      - name: Build
        run: cargo check

      - name: Run tests
        run: cargo test
